spring:
  # H2 Configuration
  datasource:
    url: jdbc:h2:mem:awsdemo
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
    platform: h2
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  h2:
    console:
      enabled: true
      path: /h2

kafka:
  bootstrap:
    servers: localhost:9092
  group:
    id: group-1

variales:
  shipment:
    uri: http://localhost:8001
